<?php $email = $this->getValueConfig('email'); ?>
<?php if(!empty($email)): ?>


<script type="text/javascript">
    //<![CDATA[

    function check() {
    	var configForm = new varienForm('config_edit_form');	
    	
    	  if (configForm.validator.validate()) {
	        new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
	            method:     'post',
	            onSuccess: function(transport){
	            	
		            if (transport.responseText){
		            	var data_response = transport.responseText.evalJSON();
		            	if(data_response.page_redirect == 0){
		            		location.reload();
		            	} else{
		            		window.location.href = data_response.url_redirect;
		            		
		            	}
		                
		            }
	            }
	        });
	     }
    }
    //]]>
</script>
<?php $name = $this->getValueConfig('name'); ?>
<h2>Olá <?php echo $name ?>, crie sua conta no Moip clicando no botão a baixo:</h2>
<?php echo $this->getButtonHtml() ?>
<?php else: ?>
	<h2>Configure sua conta moip preenchendo os dados:</h2>
<?php endif; ?>