<div class="page-title">
    <h1><?php echo $this->__('Edit Account Information') ?></h1>
</div>
<script type="text/javascript">
function getval(sel) {
		if (sel.value == "PF"){
		jQuery('#dados_pj').css('display','none');
		}
		else
		{
		jQuery('#dados_pj').css('display','block');
		}
    }
</script>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo $this->__('Account Information') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>
            </li>
            <li>
                <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                <div class="input-box">
                    <input type="text" name="email" id="email" value="<?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text required-entry validate-email" />
                </div>
            </li>
        <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
        <?php if ($_dob->isEnabled()): ?>
            <li><?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?></li>
        <?php endif ?>
        <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <li><?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?></li>
        <?php endif ?>
        <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
        <?php if ($_gender->isEnabled()): ?>
            <li><?php echo $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?></li>
        <?php endif ?>
            <li class="control">
                <input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo $this->__('Change Password') ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> class="checkbox" /><label for="change_password"><?php echo $this->__('Change Password') ?></label>
            </li>
     <?php 
$tipopessoa = Mage::getModel('eav/config')->getAttribute('customer','tipopessoa');
$razaosocial = Mage::getModel('eav/config')->getAttribute('customer','razaosocial');
$nomefantasia = Mage::getModel('eav/config')->getAttribute('customer','nomefantasia');
$cnpj = Mage::getModel('eav/config')->getAttribute('customer','cnpj');
$insestadual = Mage::getModel('eav/config')->getAttribute('customer','insestadual');
    	  $tipopessoa='<li class="wide">
            	 	                    <label for="tipopessoa" class="">Comprar como?</label>
                    <div class="input-box">
                        <select name="tipopessoa]" id="tipopessoa_select"  onchange="getval(this);">
                        	                        		<option value="PF" selected="selected">Pessoa Física</option>
                        	                        		<option value="PJ" >Pessoa Jurídica</option>
                        	                        </select>
                    </div>
		</li>';
			$nomefantasia='<div id="dados_pj" style="display:none;"><li class="fields">
					<label for="billing:nome_fantasia" class="required"><em>*</em>'.$this->__('Nome Fantasia').'</label>
						<div class="input-box">
							<input type="text" title="None Fantasia" class="input-text" name="nomefantasia" id="nomefantasia" value="'.$this->htmlEscape(Mage::getSingleton('customer/session')->getCustomer()->getNomefantasia()).'">
						</div>
		</li>';
		$razaosocial='<li class="fields">
					<label for="billing:razao_social" class="required"><em>*</em>'.$this->__('Razão Social').'</label>
						<div class="input-box">
							<input type="text" title="razaosocial" class="input-text" name="razaosocial" id="razao_social" value="'.$this->htmlEscape(Mage::getSingleton('customer/session')->getCustomer()->getRazaosocial()).'">
						</div>
		</li>';
		$cnpj='<li class="fields">
					<label for="billing:cnpj" class="required"><em>*</em>'.$this->__('CNPJ').'</label>
						<div class="input-box">
							<input type="text" title="cnpj" class="input-text" name="cnpj" id="cnpj" value="'.$this->htmlEscape(Mage::getSingleton('customer/session')->getCustomer()->getCnpj()).'" >
						</div>
		</li>';
		$insestadual='<li class="fields">
					<label for="billing:insestadual" class="required"><em>*</em>'.$this->__('Inscrição Estadual').'</label>
						<div class="input-box">
							<input type="text" title="Inscrição Estadual" class="input-text" name="insestadual" id="insestadual" value="'.$this->htmlEscape(Mage::getSingleton('customer/session')->getCustomer()->getInsestadual()).'">
						</div>
		</li>
		</div>';
echo $tipopessoa;
echo $nomefantasia;
echo $razaosocial;
echo $cnpj;
echo $insestadual;
?>
        </ul>
    </div>
    <div class="fieldset" style="display:none;">
        <h2 class="legend"><?php echo $this->__('Change Password') ?></h2>
        <ul class="form-list">
            <li>
                <label for="current_password" class="required"><em>*</em><?php echo $this->__('Current Password') ?></label>
                <div class="input-box">
                    <input type="password" title="<?php echo $this->__('Current Password') ?>" class="input-text" name="current_password" id="current_password" />
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="password" class="required"><em>*</em><?php echo $this->__('New Password') ?></label>
                    <div class="input-box">
                        <input type="password" title="<?php echo $this->__('New Password') ?>" class="input-text validate-password" name="password" id="password" />
                    </div>
                </div>
                <div class="field">
                    <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password') ?></label>
                    <div class="input-box">
                        <input type="password" title="<?php echo $this->__('Confirm New Password') ?>" class="input-text validate-cpassword" name="confirmation" id="confirmation" />
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    function setPasswordForm(arg){
        if(arg){
            $('current_password').up(3).show();
            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');

        }else{
            $('current_password').up(3).hide();
            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }
    <?php if($this->getCustomer()->getChangePassword()): ?>
        setPasswordForm(true);
    <?php endif; ?>
//]]>
</script>
